name: ci

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      PublicRelease:
        description: "Public Release"
        required: false

jobs:
  ubuntu-22_04:
    name: ubuntu-24_04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: Push'
        run: ./src/build.cmd Push
        env:
          PublicRelease: ${{ github.event.inputs.PublicRelease }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Publish: package'
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: artifacts/package